steps:
  # 1. Build the Docker container image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/apexpm:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/apexpm:latest', '.']

  # 2. Push the Docker image to the registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apexpm:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apexpm:latest']

images:
  - 'gcr.io/$PROJECT_ID/apexpm:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/apexpm:latest'

options:
  logging: CLOUD_LOGGING_ONLY
